# Generated by Django 4.2.5 on 2023-09-23 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casagrande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=255, null=True, verbose_name='Telefono')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Casagrande',
                'verbose_name_plural': 'Casagrandes',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=16, null=True, verbose_name='Cedula-Pasaporte')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, null=True, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=50, verbose_name='Genero')),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Direccion')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=12, null=True, verbose_name='Celular')),
                ('birthdate', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('imagen', models.ImageField(null=True, upload_to='img/default/')),
                ('url', models.TextField(max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=2)),
                ('limite', models.IntegerField(default=9999)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.BinaryField(null=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'numeros',
            },
        ),
        migrations.CreateModel(
            name='Sorteos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, null=True, unique=True, verbose_name='Descripcion')),
                ('costoporNumero', models.DecimalField(decimal_places=2, default=0.2, max_digits=9, verbose_name='Costo por Numero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ' Sorteo',
                'verbose_name_plural': ' Sorteo',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True, verbose_name='nombre')),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='% Comision')),
                ('id_casagrande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lottoluck.casagrande', verbose_name='id_CasaGrande')),
            ],
        ),
        migrations.CreateModel(
            name='VtasSorteo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sorteo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Sorteo')),
                ('totalventa', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('totalqty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_premio1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monto_premio2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monto_premio3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.clientes')),
                ('id_casagrande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.casagrande')),
                ('id_sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.sorteos')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='VtasDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sorteo_premio', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('numero', models.CharField(max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganador_1', models.BooleanField(default=False)),
                ('ganador_2', models.BooleanField(default=False)),
                ('ganador_3', models.BooleanField(default=False)),
                ('id_sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.sorteos')),
                ('id_vtasorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.vtassorteo')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroSorteados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('referencia', models.CharField(max_length=30, null=True, verbose_name='#LNB')),
                ('I_premio', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='IPremio')),
                ('letras', models.CharField(max_length=4, null=True, verbose_name='Letras')),
                ('serie', models.CharField(max_length=2, null=True, verbose_name='Serie')),
                ('folio', models.CharField(max_length=2, null=True, verbose_name='Folio')),
                ('II_premio', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='IIPremio')),
                ('III_premio', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='IIIPremio')),
                ('id_sorteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lottoluck.sorteos', verbose_name='tipo')),
            ],
        ),
    ]
