# Generated by Django 4.2.5 on 2023-09-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0004_clientes_date_creado_clientes_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen'),
        ),
    ]
