# Generated by Django 4.2.5 on 2023-09-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0010_clientes_tipo_cliente_alter_clientes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='tipo_cliente',
            new_name='tipocliente',
        ),
    ]
