# Generated by Django 4.2.5 on 2023-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0011_rename_tipo_cliente_clientes_tipocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=50, verbose_name='Genero'),
        ),
    ]
