# Generated by Django 4.2.5 on 2023-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0012_alter_clientes_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipocliente',
            field=models.IntegerField(choices=[[0, 'Regular'], [1, 'Especial'], [2, 'VIP'], [3, 'Compra Credido'], [4, 'Casa Grande'], [5, 'Familiar'], [8, 'Otros']], default=0, verbose_name='Tipo Cliente'),
        ),
    ]
