# Generated by Django 4.2.5 on 2023-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0014_remove_clientes_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero',
            name='url',
        ),
        migrations.AlterField(
            model_name='numero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='numeros'),
        ),
    ]
