# Generated by Django 4.2.5 on 2023-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0015_remove_numero_url_alter_numero_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
            preserve_default=False,
        ),
    ]
