# Generated by Django 4.2.5 on 2023-10-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0016_numero_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consecutivo', models.PositiveBigIntegerField(default=1)),
            ],
        ),
    ]
