# Generated by Django 4.2.5 on 2023-10-17 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0017_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtassorteo',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vtassorteo',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='vtassorteo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vtassorteo',
            name='fecha_venta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vtassorteo',
            name='id_sorteo_premio',
            field=models.IntegerField(null=True),
        ),
    ]
