# Generated by Django 4.2.5 on 2023-10-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0018_vtassorteo_descripcion_vtassorteo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtassorteo',
            name='id_casagrande',
        ),
    ]
