# Generated by Django 4.2.5 on 2023-10-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0019_remove_vtassorteo_id_casagrande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtassorteo',
            old_name='clientes',
            new_name='id_cliente',
        ),
    ]
