# Generated by Django 4.2.5 on 2023-10-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0020_rename_clientes_vtassorteo_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='lottoluck.clientes'),
        ),
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_sorteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteos', to='lottoluck.sorteos'),
        ),
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='lottoluck.vendedor'),
        ),
    ]
