# Generated by Django 4.2.5 on 2023-10-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0021_alter_vtassorteo_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtasdetalle',
            name='id_vtasorteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtasdetalles', to='lottoluck.vtassorteo'),
        ),
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.clientes'),
        ),
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_sorteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.sorteos'),
        ),
        migrations.AlterField(
            model_name='vtassorteo',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoluck.vendedor'),
        ),
    ]
