# Generated by Django 4.2.5 on 2023-10-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0023_vtassorteo_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtassorteo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
