# Generated by Django 4.2.5 on 2023-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0024_alter_vtassorteo_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtassorteo',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Facturado', 'Facturado'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=20),
        ),
    ]
