# Generated by Django 4.2.5 on 2023-10-18 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0025_alter_vtassorteo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtasdetalle',
            name='fecha_sorteo',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Sorteo'),
        ),
    ]
