# Generated by Django 4.2.5 on 2023-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0026_vtasdetalle_fecha_sorteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteos',
            name='paga1',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=9, verbose_name='Pago_Primer Premio'),
        ),
        migrations.AddField(
            model_name='sorteos',
            name='paga2',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=9, verbose_name='Pago_Segundo Premio'),
        ),
        migrations.AddField(
            model_name='sorteos',
            name='paga3',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=9, verbose_name='Pago_Tercer  Premio'),
        ),
    ]
