# Generated by Django 4.2.5 on 2023-10-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0027_sorteos_paga1_sorteos_paga2_sorteos_paga3'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtasdetalle',
            name='clientes',
            field=models.ManyToManyField(related_name='compras', to='lottoluck.clientes'),
        ),
    ]
