# Generated by Django 4.2.5 on 2023-10-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0030_remove_numerosorteados_iii_premio_relacionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtasdetalle',
            name='III_premio_relacionado',
        ),
        migrations.RemoveField(
            model_name='vtasdetalle',
            name='II_premio_relacionado',
        ),
        migrations.RemoveField(
            model_name='vtasdetalle',
            name='I_premio_relacionado',
        ),
    ]
