# Generated by Django 4.2.5 on 2023-10-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoluck', '0032_vtasdetalle_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtasdetalle',
            name='id_cliente',
        ),
    ]
